name: school_project
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.8.1 <4.0.0"  # More precise version constraint

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Firebase - Updated versions
  firebase_core: ^2.18.0
  cloud_firestore: ^4.7.0
  firebase_auth: ^4.12.0

  # State Management & DI
  flutter_riverpod: ^2.4.9
  hooks_riverpod: ^2.4.9
  flutter_hooks: ^0.20.5

  # Navigation
  go_router: ^14.0.2

  # Helpers
  fluttertoast: ^8.2.2  # Moved from dev_dependencies to main
  logger: ^2.0.2       # For better logging

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.6 # For code generation if needed

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/calm.jpg
    - assets/secure.jpg
    - assets/support.jpg
